name: Build ESP32-S3 LVGL
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: v5.0.2

      - name: Build mpy-cross
        run: make -C mpy-cross

      - name: Build MicroPython + LVGL
        run: |
          cd ports/esp32
          make BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCTAL \
          CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y \
          CONFIG_PARTITION_TABLE_CUSTOM=y \
          CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="../../../partitions-8mb.csv"

          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: micropython-esp32s3-lvgl
          path: ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCTAL/firmware.bin
