# Copyright (c) 2024 - 2025 Kevin G. Schlosser

name: macOS build
on: [push, pull_request]

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies
        run: brew install ninja sdl2 libffi

      - name: Build macOS
        run: python3 make.py macOS DISPLAY=sdl_display INDEV=sdl_pointer

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        if: always() # Wyślij nawet jeśli GitHub ma humory
        with:
          name: lvgl_macos
          path: build/
          if-no-files-found: warn

  build_esp32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: pip install Pillow

      - name: Build ESP32
        run: python3 make.py esp32 || echo "Build failed but continuing to check files"

      - name: Check files
        run: find . -name "*.bin"

      - name: Upload ESP32 Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lvgl_esp32
          path: "**/*.bin"
          if-no-files-found: warn
          if-no-files-found: error
