# Copyright (c) 2024 - 2025 Kevin G. Schlosser

name: macOS build
on:
  push:
  pull_request:

jobs:

  build_macos:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        brew install --force ninja 
        brew install --force sdl2
        brew install --force libffi
        git submodule update --init -- lib/pycparser
        git submodule update --init --jobs 4 -- lib/micropython        
        git submodule update --init --jobs 4 -- lib/lvgl

    # - name: Build STM32 port
    #   run: python3 make.py stm32 submodules clean mpy_cross BOARD=STM32H7B3I_DK DISPLAY=rgb_display INDEV=gt911

    # - name: Build Raspberry Pi PICO port
    #   run: python3 make.py rp2 submodules clean mpy_cross BOARD=RPI_PICO DISPLAY=rgb_display INDEV=gt911

    - name: Build macOS port
      run: python3 make.py macOS DISPLAY=sdl_display INDEV=sdl_pointer

    - uses: actions/upload-artifact@v4
      with:
        name: lvgl_micropy_macos
        path: build/lvgl_micropy_macos
        if-no-files-found: ignore

  build_esp32:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        brew install cmake ninja dfu-util
        pip install espressif-idf esptool wheel
        git submodule update --init -- lib/pycparser
        git submodule update --init --jobs 4 -- lib/micropython        
        git submodule update --init --jobs 4 -- lib/lvgl        

    - name: Get ESP-IDF
      run: |
        git submodule update --init --jobs 4 -- lib/esp-idf
        cd lib/esp-idf
        ./install.sh esp32s3

    - name: Build ESP32 port
      run: |
        export IDF_PATH="${GITHUB_WORKSPACE}/lib/esp-idf"
        source ./lib/esp-idf/export.sh
        # Budujemy Tw√≥j wsad S3R8 (Octal) ze sterownikami LCD i dotyku
        python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCTAL DISPLAY=rgb_display INDEV=gt911

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lvgl_micropy_esp32_s3
        path: build/*.bin
